sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t numeru/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true numeru/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-157301832043
  bucket_path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
